# Use an official Python runtime as a parent image
FROM python:2.7

# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
ADD ./src/python /app
ADD ./conf /conf

# Install any needed packages specified in requirements.txt
#RUN pip install -r /conf/requirements.txt  
RUN pip install Flask  


# Make port 8000 available to the world outside this container
EXPOSE 8000

# Define environment variable
ENV NAME Christoph

# Run app.py when the container launches
CMD ["python", "ch/cmce/litterbox-server/litterbox-server-flask.py"]